# Nossas Personas {.unnumbered}

Até o momento, definimos as seguintes Personas. Esta listagem foi criada no encontro de 22 de outubro de 2025. O objetivo destas personas é criar cenários diversos para podermos percorrer o itinerário de todos estes pacientes (personas) e identificar todas as barreiras, fragilidades e fortalezas já existentes aqui. Além disso, através delas poderemos criar em detalhes o novo modelo de cuidado.

1.  Pedro, menino, terceiro filho, 10 meses de vida, baixo peso e baixa estatura. Já se senta, mas ainda não engatinha. Sua mãe está grávida novamente e não mama mais no peito. -\> baixo peso, baixa estatura e atraso do desenvolvimento psicomotor.

2.  Carlota, 38 anos de idade, 28 semanas de gestação, G3P2 com pressão arterial 140-90 mmHg, sem queixas. Medidas anteriores normais. Nenhuma outra morbidade. Casada com o pai dos dois primeiros filhos, que hoje têm 8 e 6 anos. Gestação com doença hipertensiva da gestação.

3.  Antônio, 24 anos, casado, chega em consulta de triagem com tosse há mais de duas semanas, expectoração hemoptóica, febre, perda de peso, cansaço e muita sudorese noturna.

4.  Marcela, 27 anos, queixa de corrimento vaginal há 1 mês e sangramento e dor durante as relações sexuais. Além disso, tem emagrecimento e inapetência há mais de um mês, desde que começou a ter relações sexuais com novo parceiro há 3 meses. Está com HIV mas ainda não sabe o diagnóstico. Além disso, está com doença inflamatória pélvica (DIP) – razão do corrimento e da dispareunia.

5.  Miriam 16 anos, com amenorréia de há semanas, disúria e leucorreia e prurido. Teve duas ISTs já tratadas, com dois parceiros. Vive com os avós e é órfã de ambos os pais. Está grávida e com infecção urinária.

6.  João, 72 anos, hipertenso usando hctz, nifedinina e lisinopril e diabético com metformina, na consulta atual veio com creatinina elevada com taxa de filtração glomerular de 40 mL-minuto-1.73M2.

7.  Ana, 35 anos, professora, dor de garganta há 3 dias, febre 38ºC, odinofagia, sem tosse ou rinorreia, sem atb. Colega de trabalho com quadro semelhante. Hiperemia e exsudato purulento. Faringoamigdalite aguda.

8.  Marta, 68 anos, mulher negra, hipertensa há 5 anos, tensão sempre acima de 180/110 mmHg, há um dia notou diminuição da força do hemicorpo esquerdo, desvio da comissura labial para a direita. Provável AVC ou AIT.

9.  Paulo, 72 anos, viúvo, hipertenso com tensões em 130/80 mmHg, teve AVC há 6 meses. Agora com paresia à esquerda, marcha prejudicada. Vive com a irmã. Usa hctz 25 mg, nifedinipo 30 mg (1) e aspirina 100 mg (1) e sinvastatina 20 mg (1).

10. João, 6 anos, febre, dor articular, dor abdominal há 3 meses. Testam malária sempre com resultado negativo. Baço aumentado, dor à palpação abdominal, edema em mmii, inchaço dos dedos em mmss. descobriram que tinha anemia falciforme. Prescreveram hidroxiuréia e AINEs. Pela preocupação com possível sequestro esplênico, foi encaminhado à urgência para avaliação com o cirurgião.

11. Paulo 64 anos, viúvo, hipertenso há 20 anos e Diabético há 10 anos medicado com Lisinopril, Nifedipina e Hidroclorotiazida e Metformina. Na consulta actual com dor lombar e parestesias nos membros inferiores. Espondiloartrose anquilosante.

12. Angela 52 anos, desempregada, hipertenso há 13 anos e Diabética há 10 anos medicado com Lisinopril, Nifedipina e Hidroclorotiazida e Metformina e Glicazida. Foi mandada embora na AMODIA por falta de dinheiro das cotas mensais da associação. Decidiu fazer consultas no hospital geral da polana canico. Na consulta actual com parestesias nos membros inferiores. Ao exame físico com alteração da sensibilidade profunda e apresenta Ta:187/98 mmhg e Hemoglobina glicada de 13%.
